@formula = http://localhost:15000/formula

### Obtener todas las formulas
GET {{formula}}-all

### Ingresar una nueva formula
POST {{formula}}-new
Content-Type: application/json

{
    "bom":"5678",
    "comentario": "Prueba 2 de ingreso de formulas, salu2 jeje"
}

