@users = http://localhost:15000/users

### Get all users
GET {{users}}

### Add new user
POST {{users}}
Content-Type: application/json

{
    "num_empleado": "09071999",
    "nombre": "Enrique",
    "ap_paterno": "Alvarado",
    "ap_materno": "García",
    "departamento": "Control de Calidad",
    "tipo_usuario": 3,
    "email": "quiquealvaradogarcia@hotmail.com",
    "telefono": "5560257276",
    "img_perfil": null
}

### Get an user by id
GET {{users}}/000

### Delete an user by id
DELETE {{users}}/000