@batch = http://localhost:15000/batch

### Ver todos los lotes
GET {{batch}}-all

### Ver lote por codigo de lote
GET {{batch}}/2537

### Agregar un nuevo lote
POST {{batch}}-new
Content-Type: application/json

{
    "cod_lot": "2537",
    "id_color": 1,
    "cod_sap_color": "0130",
    "descripcion": "Rojito uwu",
    "tecnologia": 1,
    "tam_lote": "20",
    "contenedor": "Tote",
    "comentario": null
}

