@users = http://localhost:15000/users

### Get all users
GET {{users}}

### Add new user
POST {{users}}
Content-Type: application/json

{
    "num_empleado": "3",
    "nombre": "Irvin Yoariht",
    "ap_paterno": "Macedo",
    "ap_materno": "Cruz",
    "departamento": "Entonado",
    "tipo_usuario": 4,
    "email": "imacedoc1600@alumno.ipn.mx",
    "contrasena": "Yoariht1",
    "telefono": "5516369353",
    "img_perfil": null
}

### Get an user by id
GET {{users}}/000

### Delete an user by id
DELETE {{users}}/000