@users = http://localhost:15000/users

### Get all users
GET {{users}}

### Add new user
POST {{users}}
Content-Type: application/json

{
    "num_empleado": "36120911",
    "nombre": "Edgar",
    "ap_paterno": "Moran",
    "ap_materno": "Lazcano",
    "departamento": "Calidad",
    "tipo_usuario": 1,
    "email": "edgar-alexis.moran@basf.com",
    "contrasena": "2684",
    "telefono": "",
    "img_perfil": null
}

### Get an user by id
GET {{users}}/000

### Delete an user by id
DELETE {{users}}/000