@users = http://localhost:15000/users

### Get all users
GET {{users}}

### Add new user
POST {{users}}
Content-Type: application/json

{
    "num_empleado": "0",
    "nombre": "Irvin Yoariht",
    "ap_paterno": "Macedo",
    "ap_materno": "Cruz",
    "departamento": "Entonado",
    "tipo_usuario": 1,
    "email": "irvin.macedo@partners.basf.com",
    "contrasena": "",
    "telefono": "5560257276",
    "img_perfil": null
}

### Get an user by id
GET {{users}}/000

### Delete an user by id
DELETE {{users}}/000